// SNACKBAR TEXT
export const SET_SELLER_LISTING_SNACK_MESSAGE = "sellerListing/SET_SNACK_MESSAGE";
export const SET_SELLER_LISTING_LOADING = "sellerListing/SET_SELLER_LISTING_LOADING";

// SET LISTING DATA
export const SET_SELLER_LISTINGS = "sellerListing/SET_SELLER_LISTINGS";

// Update Listing Info
export const UPDATE_LISTING_ADDRESS = "sellerListing/UPDATE_LISTING_ADDRESS";
export const UPDATE_BUYER_LISTING = "sellerListing/UPDATE_BUYER_LISTING";

export const UPDATE_SUBMIT_STATUS = "sellerListing/UPDATE_SUBMIT_STATUS";
export const CLEAR_LISTING_FORM = "sellerListing/CLEAR_LISTING_FORM";